#!/usr/bin/python
# -*- coding: utf-8 -*-

import os
from fcntl import ioctl

cd_drive = '/dev/sr0'

f = os.open(cd_drive, os.O_RDONLY | os.O_NONBLOCK)
status_drive = ioctl(f, 0x5326)

if status_drive == 1:
        print("No CD in tray.")
elif status_drive == 2:
        print("CD tray opent.")
elif status_drive == 3:
        print("CD tray working.")
elif status_drive == 4:
        cd_type = ioctl(f, 0x5327)
        if cd_type == 100:
                print("Audio CD")
        elif cd_type > 100 and cd_type < 106:
                print("Data CD")
        else:
                print("No CD")
else:
        print("Unknown State.")
       
os.close(f)
